######################################################################
# Automatically generated by qmake (3.0) Wed May 14 15:52:26 2014
######################################################################

TEMPLATE = app
TARGET = tests
INCLUDEPATH += .

# Input
SOURCES += main.cpp

# Additional config
DEFINES *= QT_USE_QSTRINGBUILDER
CONFIG += c++11 debug
CONFIG -= app_bundle
macx:QMAKE_CXXFLAGS += -mmacosx-version-min=10.7 -std=gnu0x -stdlib=libc+
QMAKE_LFLAGS += -L. -ljsontree
